---
title: "Data Analysis Workflow Example Using MEM on Mass Cytometry Bead Data (UMAP, FlowSOM, MEM, RMSD)"
author: "Copyright (c) 2016-2019 by Kirsten Diggins, Sierra Barone, and Jonathan Irish, All Rights Reserved; see EULA-MEM.text for MEM license information"
date: "March 2019"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
editor_options:
  chunk_output_type: inline
---

This dataset contains 38 mass cytometry compensation beads (11,400 cells total),
each of which is supposed to be positive for only 1 marker and negative for 37. 

Each section of code should run in about 30 seconds or less. Running the entire 
script from start to finish (by choosing to Run All Chunks) should take a minute
or two. 

```{r setup, include=FALSE}
# Load all libraries
# If you get an error message, you will need to try re-installing packages by 
# going back to the 00_install_tools.RMD script
library(FlowSOM)
library(flowCore)
library(Biobase)
library(ggplot2)
library(hexbin)
library(MEM)
library(tidyverse)
library(Rtsne)
library(uwot)
library(viridis)
library(ggExtra)
library(RColorBrewer)
library(cowplot)
```

```{r MEM on beads, warning=FALSE}
# read FCS files into R
setwd(paste(getwd(), "/datafiles/MCBead", sep = ""))
file <-  dir(pattern = "*.fcs")

# Run MEM
MEM.values.orig = MEM(
  file,                     # input data (last column must contain cluster 
                            # values)
  transform = TRUE,         # arcsinh transformation of data 
  cofactor = 5,             # set cofactor
  choose.markers = FALSE,
  markers = "2,13,14,21,23:55",
  choose.ref = FALSE,       
  zero.ref = FALSE,
  rename.markers = FALSE,
  file.is.clust = FALSE,
  add.fileID = FALSE,
  IQR.thresh = NULL
)

# build MEM heatmap and output enrichment scores
build.heatmaps(
  MEM.values.orig,           # input MEM values
  cluster.MEM = "none",
  display.thresh = 1,
  newWindow.heatmaps = FALSE,
  output.files = FALSE,
  labels = FALSE,
  only.MEMheatmap = TRUE
)

# prepare data for use in UMAP and downstream analysis
FCS = read.FCS(file)
data.df = as.data.frame(FCS@exprs)
chosen.markers = data.df[, c(2, 13, 14, 21, 23:55)]
transformed.chosen.markers <- chosen.markers %>%
  mutate_all(function(x)
    asinh(x / 5))

# set seed for reproducible results
overall_seed = 43
```

```{r UMAP}
# Run UMAP on 37 chosen markers
set.seed(overall_seed)
myumap <- umap(transformed.chosen.markers, 
               ret_model = TRUE, 
               n_threads = 1,
               verbose = TRUE)
umap.data = as.data.frame(myumap$embedding)

range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1]/range[2])

# UMAP flat dot plot and density dot plot
UMAP.plot <- data.frame(x = umap.data[,1], y = umap.data[,2])

ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + 
  geom_point(aes(x=x, y=y), cex = 1) + labs( x = "UMAP 1", y = "UMAP 2", 
        title = "Mass Cytometry Beads") + theme_bw()

# density dot plot
ggplot(UMAP.plot, aes(x = x, y = y)) + 
  coord_fixed(ratio = graphical.ratio)+ geom_point(size = 0.5) +geom_density_2d_filled(bins = 29) +scale_fill_manual(values = c("NA","NA","NA","NA","NA","NA","NA",viridis::viridis(24,option = "A"))) +
labs(x = "UMAP 1", y = "UMAP 2", 
  title = "Density on UMAP Axes - MC Beads") + theme_bw()  + 
  theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank())+theme(legend.position = "none") +ylim(1.2*min(umap.data[,2]),1.2*max(umap.data[,2]))+xlim(1.2*min(umap.data[,1]),1.2*max(umap.data[,1]))
```

```{r plot heat on markers UMAP}
setwd(paste(getwd(), "/datafiles/MCBead", sep = ""))
dir.create("./output files/")

UMAP.by.marker<-as_tibble(umap.data) %>%
  bind_cols(transformed.chosen.markers)  %>%
  gather(channel, intensity, -V1, -V2) %>%
  mutate(across(channel,factor))%>%
  group_split(channel) %>%
  map(
    ~ggplot(.,aes(x= V1, y= V2, col = intensity)) +
  geom_point(size = 3) +
  scale_color_gradientn(
    colours = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(5))+
  facet_grid(~ channel, labeller = function(x) label_value(x, multi_line = FALSE)) +
  coord_fixed() +
  theme_bw()+
  theme(strip.text.x = element_text(size = 20),legend.title=element_blank()))%>%
  plot_grid(plotlist = ., align = 'hv', ncol = 8)

png(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"UMAP on transformed data.png"),height = 2000,width = 4000)
print(UMAP.by.marker)
dev.off()
```

```{r FlowSOM on UMAP}
# Run FlowSOM on the UMAP axes
umap.mat <- as.matrix(umap.data)

# create flowFrame
UMAP.metadata <-
  data.frame(name = dimnames(umap.mat)[[2]],
             desc = paste('UMAP', dimnames(umap.mat)[[2]]))
UMAP.metadata$range <- apply(apply(umap.mat, 2, range), 2, diff)
UMAP.metadata$minRange <- apply(umap.mat, 2, min)
UMAP.metadata$maxRange <- apply(umap.mat, 2, max)
umap.flowframe <- new("flowFrame",
                      exprs = umap.mat,
                      parameters = AnnotatedDataFrame(UMAP.metadata))

# implement the FlowSOM on the UMAP axes
fsom <-
  FlowSOM(
    umap.flowframe,
    colsToUse = c(1:2),
    nClus = 38,
    seed = overall_seed
  )
FlowSOM.clusters <-
  GetMetaclusters(fsom)

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, 
                           rownames(qual_col_pals)))
values = sample(col_vector)

# plot FlowSOM clusters on UMAP axes
ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + 
  geom_point(aes(x=x, y=y, color=FlowSOM.clusters),cex = 1.5) + 
  guides(colour = guide_legend(override.aes = list(size=5), nrow = 13)) +
  labs(x = "UMAP 1", y = "UMAP 2",title = "FlowSOM Clustering on UMAP Axes", 
       color = "FlowSOM Cluster") + theme_bw() + 
  scale_color_manual(values = values)  
```

```{r MEM on UMAP/FlowSOM Clusters}
setwd(paste(getwd(), "/datafiles/MCBead", sep = ""))

# Run MEM on the FlowSOM clusters found by using the UMAP axes
cluster = as.numeric(as.vector((FlowSOM.clusters)))
MEM.data = cbind(transformed.chosen.markers, cluster)

MEM.values.uf = MEM(
  MEM.data,
  transform = FALSE,
  cofactor = 5,
  choose.markers = FALSE,
  markers = "all",
  choose.ref = FALSE,
  zero.ref = FALSE,
  rename.markers = FALSE,
  file.is.clust = FALSE,
  add.fileID = FALSE,
  IQR.thresh = NULL
)

# build MEM heatmap and output enrichment scores
build.heatmaps(
  MEM.values.uf,
  cluster.MEM = "none",
  cluster.medians = "none",
  display.thresh = 1,
  newWindow.heatmaps = FALSE,
  output.files = TRUE,
  labels = FALSE,
  only.MEMheatmap = TRUE
)
```


```{r RMSD for All Clusters}
setwd(paste(getwd(), "/datafiles/MCBead", sep = ""))
# RMSD to compare labels from all populations
orig.MEM.scores = as.data.frame(MEM.values.orig[[5]])
rownames(orig.MEM.scores) = paste0(rownames(orig.MEM.scores), " Manual")
uf.MEM.scores = as.data.frame(MEM.values.uf[[5]])
rownames(uf.MEM.scores) = paste0(rownames(uf.MEM.scores), ' UMAP')
all.MEM.values = as.matrix(rbind(uf.MEM.scores, orig.MEM.scores))

RMSD_vals <-
  MEM_RMSD(
    all.MEM.values,
    format = NULL,
    newWindow.heatmaps = FALSE,
    output.matrix = TRUE
  )
```
