---
title: "Data Analysis Workflow Example on Your Data (UMAP, FlowSOM, MEM)"
author: "Copyright (c) 2016-2019 by Kirsten Diggins, Sierra Barone, and Jonathan Irish, All Rights Reserved; see EULA-MEM.text for MEM license information"
date: "July 2019"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---
```{r setup, include=FALSE}
# Load all libraries
# If you get an error message, you will need to try re-installing packages by 
# going back to the 00_install_tools.RMD script
library(FlowSOM)
library(flowCore)
library(Biobase)
library(ggplot2)
library(MEM)
library(tidyverse)
library(Rtsne)
library(uwot)
library(RColorBrewer)

choose.markers <- function(exp_data) {
    print("Numbered column names, in order they appear in file: ")
    print(paste(c(1:(ncol(exp_data))), ": ", 
                colnames(exp_data[, c(1:(ncol(exp_data)))]), sep = ""))
    markers = readline("Enter column numbers to include (e.g. 1:5,6,8:10).\n")
    sep_vals = unlist(strsplit(markers, ","))
    list_vals = vector()
    for (i in 1:length(sep_vals)) {
        val = sep_vals[i]
        if (length(unlist(strsplit(val, ":"))) > 1) {
            new_val = as.numeric(unlist(strsplit(val, ":"))[1]):
              as.numeric(unlist(strsplit(val, ":"))[2])
        } else{
            new_val = as.numeric(sep_vals[i])
        }
        list_vals = c(list_vals, new_val)
    }
    markerList = c(list_vals)
    return(markerList)
}
```

```{r read_data_files_fcs, warning=FALSE}
# read FCS files into R; make sure FCS files are in the my_data_files folder 
setwd(paste(getwd(), "/datafiles/my_data_files", sep = ""))

my.files <-  dir(pattern = "*.fcs")

data.lists <- lapply(lapply(my.files, read.FCS), exprs)

# variable my.data in environment should contain a concatenation of all cells
# and all measure features 
my.data = as.data.frame(do.call(rbind, mapply(cbind, data.lists, "File ID" = 
                                        c(1:length(data.lists)), SIMPLIFY = F)))
colnames(my.data)[1:length(my.data) - 1] <- as.character(read.FCS
(my.files[[1]])@parameters@data[["desc"]])
```
```{r read_data_files_csv, warning=FALSE}
# read FCS files into R; make sure FCS files are in the my_data_files folder 
setwd(paste(getwd(), "/datafiles/my_data_files", sep = ""))

my.files <-  dir(pattern = "*.csv")

data.lists <- lapply(my.files, read.csv)

# variable my.data in environment should contain a concatenation of all cells
# and all measure features 
my.data = as.data.frame(do.call(rbind, mapply(cbind, data.lists, "File ID" = 
                                        c(1:length(data.lists)), SIMPLIFY = F)))
```
```{r select_and_scale}
# select all channels with markers (that you want to apply scales to) by opening
# console below
my.marker.data = as.data.frame(as.data.frame(my.data)[,c(choose.markers(my.data))])

# set the cofactor for all features
cofactor = 5

# if all of your channels have the same cofactor, this will apply an arcsih
# transformation to the previously selected markers
my.markers.transformed <- my.marker.data %>%
  mutate_all(function(x)
    asinh(x / cofactor))
```
```{r run_UMAP}
# Run UMAP on chosen markers

# select all channels to use in UMAP by opening console below similar to
# what you did previously
umap.markers = as.data.frame(as.data.frame(my.markers.transformed)[,c(choose.markers(my.markers.transformed))])

myumap <- umap(umap.markers, 
               ret_model = TRUE, 
               verbose = TRUE)
umap.data = as.data.frame(myumap$embedding)
colnames(umap.data) <- c("UMAP1", "UMAP2")

range <- apply(apply(umap.data, 2, range), 2, diff)
graphical.ratio <- (range[1]/range[2])

# UMAP flat dot plot and density dot plot (1 dot = 1 cell)
UMAP.plot <- data.frame(x = umap.data[,1], y = umap.data[,2])

ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + geom_point(aes(x=x, y=y), cex = 1) + labs( x = "UMAP 1", y = "UMAP 2") + theme_bw()

ggplot(UMAP.plot, aes(x=x, y=y)) + coord_fixed(ratio = graphical.ratio)  + geom_bin2d(bins = 128) + 
  scale_fill_viridis_c(option = "A", trans = "sqrt") + scale_x_continuous(expand = c(0.1,0)) + 
  scale_y_continuous(expand = c(0.1,0)) + labs(x = "UMAP 1", y = "UMAP 2") + theme_bw()
```

```{r run_FlowSOM_on_UMAP}
# enter target number of clusters
target.clusters = 20

# Run FlowSOM on your selected variable
flowsom.input = umap.data
mat <- as.matrix(flowsom.input)

# create flowFrame for FlowSOM input
metadata <-
  data.frame(name = dimnames(mat)[[2]],
             desc = dimnames(mat)[[2]])
metadata$range <- apply(apply(mat, 2, range), 2, diff)
metadata$minRange <- apply(mat, 2, min)
metadata$maxRange <- apply(mat, 2, max)
input.flowframe <- new("flowFrame",
                      exprs = mat,
                      parameters = AnnotatedDataFrame(metadata))

# implement the FlowSOM on the data
fsom <-
  FlowSOM(
    input.flowframe,
    colsToUse = c(1:2),
    nClus = target.clusters,
    seed = 1
  )
FlowSOM.clusters <-
  as.matrix(fsom[[2]][fsom[[1]]$map$mapping[, 1]])

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, 
                           rownames(qual_col_pals)))
col_vector = col_vector[-c(4,17,19,27,29:45)]
values = sample(col_vector)

# plot FlowSOM clusters on UMAP axes
ggplot(UMAP.plot) + coord_fixed(ratio=graphical.ratio) + 
  geom_point(aes(x=x, y=y, color=FlowSOM.clusters),cex = 1.5) + 
  guides(colour = guide_legend(override.aes = list(size=5), nrow = 13)) +
  labs(x = "UMAP 1", y = "UMAP 2",title = "FlowSOM Clustering on UMAP Axes", 
       color = "FlowSOM Cluster") + theme_bw() + 
  scale_color_manual(values = values)  

cluster = as.numeric(as.vector((FlowSOM.clusters)))
```

```{r run_MEM_on_Clusters}
# Run MEM on the FlowSOM clusters found by using UMAP axes
cluster = as.numeric(as.vector((FlowSOM.clusters)))
# Run MEM on the FlowSOM clusters from UMAP
MEM.data = cbind(my.markers.transformed, cluster)

MEM.values.uf = MEM(
  MEM.data,
  transform = FALSE,
  cofactor = 0,
  choose.markers = FALSE,
  markers = "all",
  choose.ref = FALSE,
  zero.ref = FALSE,
  rename.markers = FALSE,
  new.marker.names = "none",
  file.is.clust = FALSE,
  add.fileID = FALSE,
  IQR.thresh = NULL
)

# build MEM heatmap and output enrichment scores
build.heatmaps(
  MEM.values.uf,
  cluster.MEM = "both",
  cluster.medians = "none",
  display.thresh = 1,
  newWindow.heatmaps = TRUE,
  output.files = TRUE,
  labels = FALSE,
  only.MEMheatmap = TRUE
)
```

```{r export_files_fcs}
dir.create(file.path(getwd(), "/datafiles/my_data_files/output files"), showWarnings = FALSE)
setwd(paste(getwd(), "/datafiles/my_data_files/output files", sep = ""))

data.to.export = cbind(my.data,umap.data,cluster)
separate.files = split(data.to.export,data.to.export$`File ID`)
for (i in 1:length(separate.files)){
  single.file = separate.files[[i]]
  remove.ID  = single.file[-c(ncol(my.data))]
  mat <- as.matrix(single.file)
# create flowFrame
metadata <-
  data.frame(name = dimnames(mat)[[2]],
             desc = dimnames(mat)[[2]])
metadata$range <- apply(apply(mat, 2, range), 2, diff)
metadata$minRange <- apply(mat, 2, min)
metadata$maxRange <- apply(mat, 2, max)
export.flowframe <- new("flowFrame",
                      exprs = mat,
                      parameters = AnnotatedDataFrame(metadata))
newname  = str_remove(my.files[i], ".fcs")
  filename = paste0(newname,"_UMAP_FlowSOM.fcs")
  write.FCS(export.flowframe,filename = filename)
  print(i)}
```

```{r export_files csv}
dir.create(file.path(getwd(), "/datafiles/my_data_files/output files"), showWarnings = FALSE)
setwd(paste(getwd(), "/datafiles/my_data_files/output files", sep = ""))

data.to.export = cbind(my.data,umap.data,cluster)
separate.files = split(data.to.export,data.to.export$`File ID`)
for (i in 1:length(separate.files)){
  single.file = separate.files[[i]]
  remove.ID  = single.file[-c(ncol(my.data))]
  newname  = str_remove(my.files[i], ".csv")
  filename = paste0(newname,"_UMAP_FlowSOM.csv")
  write.csv(single.file,file = filename)
  print(i)}
```
